simple_oauth_pkce.settings:
  type: config_object
  label: 'Simple OAuth PKCE settings'
  mapping:
    enforcement:
      type: string
      label: 'PKCE Enforcement Level'
    s256_enabled:
      type: boolean
      label: 'Enable S256 Challenge Method'
    plain_enabled:
      type: boolean
      label: 'Enable Plain Challenge Method'
