simple_oauth_21.debug:
  type: config_object
  label: 'Simple OAuth 2.1 Debug Configuration'
  mapping:
    form_serialization_debugging:
      type: boolean
      label: 'Enable form serialization debugging'
      description: 'Enable detailed logging and analysis of form serialization issues. Should only be enabled in development environments.'
    log_level:
      type: string
      label: 'Debug log level'
      description: 'Minimum log level for debugging output'
    max_recursion_depth:
      type: integer
      label: 'Maximum recursion depth'
      description: 'Maximum depth for form element inspection to prevent infinite loops'
